esphome:
  name: esp_neotrellis
  platform: ESP8266
  board: huzzah
  includes:
    - comm.h

wifi:
  ssid: "TreeHouseNet"
  password: "HereIsTheTreeHouseHaveABeer"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp_neotrellis Fallback Hotspot"
    password: "o5djHKmXz26z"

captive_portal:

# Enable logging
logger:
  baud_rate: 0
  logs:
    uart_esp8266: NONE

# Enable Home Assistant API
api:

ota:

# Component
custom_component:
  - lambda: |-
      auto my_comm_component = new CommCustomComponent(my_uart);
      return {my_comm_component};
uart:
  tx_pin: 15
  rx_pin: 13
  baud_rate: 115200
  id: my_uart
